format = """
[](color1)\
$username\
[](color1)\
[ ]()\
[](color4)\
$directory\
[](color4)\
$git_branch\
$git_status\
[ ]()\
"""

right_format = """
[](color2)\
$cmd_duration\
[](color2)\
"""

add_newline = false

palette = 'colors'

[palettes.colors]
color1 = '#c7bfff'
color2 = '#e5deff'
color3 = '#141318'
color4 = '#c8c2e9'
color5 = '#5b51a3'

[username]
show_always = true
style_user = "bold fg:color3 bg:color1"
style_root = "bg:#9A348E"
format = '[$user󰧞linux]($style)'
disabled = false

[directory]
style = "bold fg:color3 bg:color4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bold color5"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bold fg:#FF9700"
format = '[$all_status$ahead_behind]($style)'

[cmd_duration]
min_time = 0
style = "bold fg:color3 bg:color2"
format = '[$duration]($style)'
