format = """
[](color1)\
$os\
$username\
[](color1)\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
[ ]()\
[](color2)\
$time\
[](color2)\
[ ]()\
"""

add_newline = false

palette = 'colors'

[palettes.colors]
color1 = '#ffade1'
color2 = '#ffd8ed'
color3 = '#1e100c'

[username]
show_always = true
style_user = "bold fg:color3 bg:color1"
style_root = "bg:#9A348E"
format = '[$user]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true

[directory]
style = "bold fg:#4DD2FF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " 󰮯 "
"Documents" = " 󰈙 "
"Downloads" = "   "
"Music" = "   "
"Pictures" = "   "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bold #FF9700"
format = '[$symbol $branch]($style)'

[git_status]
style = "bold fg:#FF9700"
format = '[$all_status$ahead_behind]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bold fg:color3 bg:color2"
format = '[󰥔 $time]($style)'
