$image = {{image}}

$primary           = rgba({{colors.primary.default.hex_stripped}}ff)
$primary_fixed     = rgba({{colors.primary_fixed.default.hex_stripped}}ff)
$primary_fixed_dim = rgba({{colors.primary_fixed_dim.default.hex_stripped}}ff)

$surface_container      = rgba({{colors.surface_container.default.hex_stripped}}ff)
$surface_container_high = rgba({{colors.surface_container_high.default.hex_stripped}}ff)

$border = {{colors.primary.default.rgba | set_alpha: 0.7}}
$box    = {{colors.primary.default.rgba | set_alpha: 0.1}}
$red    = {{colors.red.default.rgba}}
$green  = {{colors.green.default.rgba}}
